/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonedShotchartRouteImport } from './routes/zoned-shotchart'
import { Route as HalfcourtRouteImport } from './routes/halfcourt'
import { Route as IndexRouteImport } from './routes/index'

const ZonedShotchartRoute = ZonedShotchartRouteImport.update({
  id: '/zoned-shotchart',
  path: '/zoned-shotchart',
  getParentRoute: () => rootRouteImport,
} as any)
const HalfcourtRoute = HalfcourtRouteImport.update({
  id: '/halfcourt',
  path: '/halfcourt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/halfcourt': typeof HalfcourtRoute
  '/zoned-shotchart': typeof ZonedShotchartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/halfcourt': typeof HalfcourtRoute
  '/zoned-shotchart': typeof ZonedShotchartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/halfcourt': typeof HalfcourtRoute
  '/zoned-shotchart': typeof ZonedShotchartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/halfcourt' | '/zoned-shotchart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/halfcourt' | '/zoned-shotchart'
  id: '__root__' | '/' | '/halfcourt' | '/zoned-shotchart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HalfcourtRoute: typeof HalfcourtRoute
  ZonedShotchartRoute: typeof ZonedShotchartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoned-shotchart': {
      id: '/zoned-shotchart'
      path: '/zoned-shotchart'
      fullPath: '/zoned-shotchart'
      preLoaderRoute: typeof ZonedShotchartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halfcourt': {
      id: '/halfcourt'
      path: '/halfcourt'
      fullPath: '/halfcourt'
      preLoaderRoute: typeof HalfcourtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HalfcourtRoute: HalfcourtRoute,
  ZonedShotchartRoute: ZonedShotchartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
